os: osx
osx_image: xcode10.1

language: node_js
node_js: '10'

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $ELECTRON_CACHE
    - $ELECTRON_BUILDER_CACHE

install:
  - yarn --frozen-lockfile

script:
  - yarn test && yarn dist --win

before_cache:
  - rm -rf $ELECTRON_BUILDER_CACHE/wine

branches:
  except:
    - '/^v\\d+\\.\\d+\\.\\d+$/'

notifications:
  email: false
